DATES
1  JUL  2021 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_21_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_21_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_21_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_21_2@  1* 10000 /
/

DATES
1  JAN  2022 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_22_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_22_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_22_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_22_1@  1* 10000 /
/

DATES
1  JUL  2022 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_22_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_22_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_22_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_22_2@  1* 10000 /
/

DATES
1  JAN  2023 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_23_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_23_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_23_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_23_1@  1* 10000 /
/

DATES
1  JUL  2023 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_23_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_23_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_23_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_23_2@  1* 10000 /
/

DATES
1  JAN  2024 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_24_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_24_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_24_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_24_1@  1* 10000 /
/

DATES
1  JUL  2024 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_24_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_24_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_24_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_24_2@  1* 10000 /
/

DATES
1  JAN  2025 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_25_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_25_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_25_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_25_1@  1* 10000 /
/

DATES
1  JUL  2025 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_25_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_25_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_25_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_25_2@  1* 10000 /
/

DATES
1  JAN  2026 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_26_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_26_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_26_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_26_1@  1* 10000 /
/

DATES
1  JUL  2026 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_26_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_26_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_26_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_26_2@  1* 10000 /
/

DATES
1  JAN  2027 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_27_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_27_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_27_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_27_1@  1* 10000 /
/

DATES
1  JUL  2027 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_27_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_27_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_27_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_27_2@  1* 10000 /
/

DATES
1  JAN  2028 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_28_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_28_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_28_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_28_1@  1* 10000 /
/

DATES
1  JUL  2028 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_28_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_28_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_28_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_28_2@  1* 10000 /
/

DATES
1  JAN  2029 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_29_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_29_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_29_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_29_1@  1* 10000 /
/

DATES
1  JUL  2029 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_29_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_29_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_29_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_29_2@  1* 10000 /
/

DATES
1  JAN  2030 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_30_1@  /
P2   OPEN   BHP   5*                             @P2_PRS_30_1@  /
P3   OPEN   BHP   5*                             @P3_PRS_30_1@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_30_1@  1* 10000 /
/

DATES
1  JUL  2030 /
/

WCONPROD
--name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
P1   OPEN   BHP   5*                             @P1_PRS_30_2@  /
P2   OPEN   BHP   5*                             @P2_PRS_30_2@  /
P3   OPEN   BHP   5*                             @P3_PRS_30_2@  /
/

WCONINJE
--name  type   flag   cntrl   pres/surfaceQ --1500
I1   WATER    OPEN    RATE   @I1_RTE_30_2@  1* 10000 /
/

DATES
1  JAN  2031 /
/
--
--WCONPROD
----name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
--P1   OPEN   BHP   5*                             @P1_PRS_31_1@  /
--P2   OPEN   BHP   5*                             @P2_PRS_31_1@  /
--P3   OPEN   BHP   5*                             @P3_PRS_31_1@  /
--/
--
--WCONINJE
----name  type   flag   cntrl   pres/surfaceQ --1500
--I1   WATER    OPEN    RATE   @I1_RTE_31_1@  1* 10000 /
--/
--
--DATES
--1  JUL  2031 /
--/
--
--WCONPROD
----name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
--P1   OPEN   BHP   5*                             @P1_PRS_31_2@  /
--P2   OPEN   BHP   5*                             @P2_PRS_31_2@  /
--P3   OPEN   BHP   5*                             @P3_PRS_31_2@  /
--/
--
--WCONINJE
----name  type   flag   cntrl   pres/surfaceQ --1500
--I1   WATER    OPEN    RATE   @I1_RTE_31_2@  1* 10000 /
--/
--
--DATES
--1  JAN  2032 /
--/
--
--WCONPROD
----name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
--P1   OPEN   BHP   5*                             @P1_PRS_32_1@  /
--P2   OPEN   BHP   5*                             @P2_PRS_32_1@  /
--P3   OPEN   BHP   5*                             @P3_PRS_32_1@  /
--/
--
--WCONINJE
----name  type   flag   cntrl   pres/surfaceQ --1500
--I1   WATER    OPEN    RATE   @I1_RTE_32_1@  1* 10000 /
--/
--
--DATES
--1  JUL  2032 /
--/
--
--WCONPROD
----name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
--P1   OPEN   BHP   5*                             @P1_PRS_32_2@  /
--P2   OPEN   BHP   5*                             @P2_PRS_32_2@  /
--P3   OPEN   BHP   5*                             @P3_PRS_32_2@  /
--/
--
--WCONINJE
----name  type   flag   cntrl   pres/surfaceQ --1500
--I1   WATER    OPEN    RATE   @I1_RTE_32_2@  1* 10000 /
--/
--
--DATES
--1  JAN  2033 /
--/
--
--WCONPROD
----name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
--P1   OPEN   BHP   5*                             @P1_PRS_33_1@  /
--P2   OPEN   BHP   5*                             @P2_PRS_33_1@  /
--P3   OPEN   BHP   5*                             @P3_PRS_33_1@  /
--/
--
--WCONINJE
----name  type   flag   cntrl   pres/surfaceQ --1500
--I1   WATER    OPEN    RATE   @I1_RTE_33_1@  1* 10000 /
--/
--
--DATES
--1  JUL  2033 /
--/
--
--WCONPROD
----name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
--P1   OPEN   BHP   5*                             @P1_PRS_33_2@  /
--P2   OPEN   BHP   5*                             @P2_PRS_33_2@  /
--P3   OPEN   BHP   5*                             @P3_PRS_33_2@  /
--/
--
--WCONINJE
----name  type   flag   cntrl   pres/surfaceQ --1500
--I1   WATER    OPEN    RATE   @I1_RTE_33_2@  1* 10000 /
--/
--
--DATES
--1  JAN  2034 /
--/

--WCONPROD
----name flag  cntrl  OratT WatT  GasT  LiqT   ResvT  BHPT  THPT
--P1   OPEN   BHP   5*                             @P1_PRS_34_1@  /
--P2   OPEN   BHP   5*                             @P2_PRS_34_1@  /
--P3   OPEN   BHP   5*                             @P3_PRS_34_1@  /
--/
--
--WCONINJE
----name  type   flag   cntrl   pres/surfaceQ --1500
--I1   WATER    OPEN    RATE   @I1_RTE_34_1@  1* 10000 /
--/