--Field quantities
-- Field oil prod rate.
--FOPR
-- Oil Production Rate History
--FOPRH
-- Oil Production Total
FOPT

FWPT
-- Average pressure for field
--FPR
-- Instantaneous GOR for field
FGOR
-- Field wat inj rate
FWIT
-- Aquifer influx rate for field
--FAQR
-- Instantaneous water cuts for field
--FWCT
-- Oil saturation, Region
ROSAT
/

--INCLUDE
--BSOL.INC /
--/
--BSOIL
--1 1	1
--1 2 1
--1 3 1
--1 4	1
--1 5 1
--/

RWSAT
/

--FVPR
--FVIR
FOE
/
--FOEIW
--Well quantities
WOPR
/
WOPT
/
WWCT
/
WGOR
/
WBHP
/
WWPR
/
WWIR
/


--Miscellaneous and output control keywords
RUNSUM
SEPARATE
--EXCEL
--NARROW
--/